; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
;   This file defines common HexaOS environment. For environment-specific, use hexaos_envs.ini

[platformio]
description                     = HexaOS - ESP32 Universal Operating System and Development Platform.
src_dir                         = src
lib_dir                         = lib/common
boards_dir                      = environment/boards
build_cache_dir                 = .cache
extra_configs                   = environment/envs/hexaos_envs.ini           ; We shall update later. 
default_envs                    = hexaos_esp32p4_es

; HexaOS Common build parameters for each env.

[common]
platform                        = https://github.com/TheHexaMaster/platform-espressif32/archive/refs/tags/h1.0.2.zip
platform_packages               =
framework                       = arduino
board                           = esp32
board_build.filesystem          = littlefs
board_build.littlefs_version    = 2.0
board_build.variants_dir        = environment/boards/variants
custom_unpack_dir               = unpacked_littlefs
monitor_speed                   = 115200
monitor_echo                    = no
upload_resetmethod              = nodemcu
check_skip_packages             = yes
lib_archive                     = no
lib_ldf_mode                    = chain
lib_compat_mode                 = strict
shared_libdeps_dir              = lib
lib_extra_dirs                  =
lib_ignore                  =
build_unflags               = -Wswitch-unreachable
                              -Wstringop-overflow
                              -Wincompatible-pointer-types
                              -Wnonnull-compare
                              -fexceptions
                              -Wpointer-arith
                              -Wall
                              -Wdeprecated-declarations
build_flags                 = -Wl,-Map,firmware.map
                              -Wno-deprecated-declarations
                              -Wreturn-type
                              -Wno-switch-unreachable
                              -Wno-stringop-overflow
                              -fno-exceptions
                              -ffunction-sections
                              -fdata-sections
                              -Wl,--gc-sections
                              -D HEXAOS_VERSION=\"0.0.1-alpha\"
extra_scripts               = pre:environment/scripts/pre/addcflags.py
                              pre:environment/scripts/pio_prebuild_hx_layout.py
monitor_filters             =
custom_component_remove     = espressif/esp_ipa

[env:hexaos_common]
framework                   = ${common.framework}
platform                    = ${common.platform}
platform_packages           = ${common.platform_packages}
board_build.filesystem      = ${common.board_build.filesystem}
custom_unpack_dir           = ${common.custom_unpack_dir}
board_build.variants_dir    = ${common.board_build.variants_dir}
board                       = ${common.board}
monitor_speed               = ${common.monitor_speed}
monitor_echo                = ${common.monitor_echo}
upload_resetmethod          = ${common.upload_resetmethod}
check_skip_packages         = ${common.check_skip_packages}
extra_scripts               = ${common.extra_scripts}
monitor_filters             = ${common.monitor_filters}
build_unflags               = ${common.build_unflags}
build_flags                 = ${common.build_flags}
lib_ldf_mode                = ${common.lib_ldf_mode}
lib_compat_mode             = ${common.lib_compat_mode}
lib_extra_dirs              = ${common.lib_extra_dirs}
lib_ignore                  = ${common.lib_ignore}
custom_component_remove     = ${common.custom_component_remove}
custom_files_upload         = no_files
 