; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
;   This file defines common HexaOS environment. For environment-specific, use hexaos_envs.ini

[platformio]
description                     = HexaOS - ESP32 Universal Operating System and Development Platform.
src_dir                         = src
lib_dir                         = lib/common
boards_dir                      = environment/boards
build_cache_dir                 = .cache
extra_configs                   = environment/envs/hexaos_envs.ini           ; We shall update later. 

; HexaOS Common build parameters for each env.

[common]
platform                        = https://github.com/TheHexaMaster/platform-espressif32/archive/refs/tags/h1.0.2.zip
platform_packages               =
framework                       = arduino
board                           = esp32
board_build.filesystem          = littlefs
board_build.littlefs_version    = 2.0
board_build.variants_dir        = environment/boards/variants
custom_unpack_dir               = unpacked_littlefs
monitor_speed                   = 115200
monitor_echo                    = yes
upload_resetmethod              = nodemcu
check_skip_packages             = yes
lib_archive                     = no
lib_ldf_mode                    = chain
lib_compat_mode                 = strict
shared_libdeps_dir              = lib
lib_extra_dirs                  =
lib_ignore                  =
build_unflags               = -Wswitch-unreachable
                              -Wstringop-overflow
                              -Wincompatible-pointer-types
                              -Wnonnull-compare
                              -fexceptions
                              -Wpointer-arith
                              -Wall
                              -Wdeprecated-declarations
build_flags                 = -Wl,-Map,firmware.map
                              -Wno-deprecated-declarations
                              -Wreturn-type
                              -Wno-switch-unreachable
                              -Wno-stringop-overflow
                              -fno-exceptions
                              -ffunction-sections
                              -fdata-sections
                              -Wl,--gc-sections
                              -D HEXAOS_VERSION=\"0.0.1-alpha\"
extra_scripts               = pre:environment/scripts/pre/addcflags.py
monitor_filters             =
custom_component_remove     = espressif/esp_ipa