/*
  HexaOS - hx_build_layout_autogen.h

  Copyright (C) 2026 Martin Macak
  SPDX-License-Identifier: GPL-3.0-only

  Description
  Auto-generated build layout defaults produced from pins_arduino.h and hx_build.h.
  Do not edit this file manually. Regenerate it from the prebuild step.
*/

#pragma once

#define HX_BUILD_DEFAULT_BOARD_PINMAP_JSON "[0,0,0,0,0,0,0,200,201,0,0,0,0,0,802,803,804,805,800,801,0,0,0,0,0,0,0,0,708,706,707,700,202,203,704,705,0,101,100,0,0,0,0,0,0,0,0,0,0,703,709,702,701,0,806]"
#define HX_BUILD_DEFAULT_DRIVERS_BINDINGS_JSON "{}"
