/*
  HexaOS - hx_target_caps.h

  Copyright (C) 2026 Martin Macak
  SPDX-License-Identifier: GPL-3.0-only

  Description
  Static target capability database derived from the target-oriented view used
  in Tasmota templates. This file intentionally describes only coarse, stable,
  target-level GPIO facts such as count, analog availability, touch support,
  strap pins, flash-reserved pins, PSRAM-reserved pins, USB pins, and input-only
  restrictions.

  It does not try to encode the full ESP-IDF GPIO matrix or every peripheral mux
  possibility. The role of this database is validation of board.pinmap and
  board.bindings, not replacement of vendor datasheets.
*/

#pragma once

#include <stdint.h>

// GPIO capability flags.
#define HX_GPIO_CAP_VALID         0x0001u
#define HX_GPIO_CAP_INPUT         0x0002u
#define HX_GPIO_CAP_OUTPUT        0x0004u
#define HX_GPIO_CAP_ANALOG        0x0008u
#define HX_GPIO_CAP_TOUCH         0x0010u
#define HX_GPIO_CAP_LOWPOWER      0x0020u
#define HX_GPIO_CAP_STRAP         0x0040u
#define HX_GPIO_CAP_FLASH         0x0080u
#define HX_GPIO_CAP_PSRAM         0x0100u
#define HX_GPIO_CAP_USB           0x0200u
#define HX_GPIO_CAP_INPUT_ONLY    0x0400u
#define HX_GPIO_CAP_DEFAULT_TX0   0x0800u
#define HX_GPIO_CAP_DEFAULT_RX0   0x1000u

#define HX_GPIO_CAP_IO   (HX_GPIO_CAP_VALID | HX_GPIO_CAP_INPUT | HX_GPIO_CAP_OUTPUT)
#define HX_GPIO_CAP_AIO  (HX_GPIO_CAP_IO | HX_GPIO_CAP_ANALOG)
#define HX_GPIO_CAP_IN   (HX_GPIO_CAP_VALID | HX_GPIO_CAP_INPUT)

enum HxTargetKind : uint8_t {
  HX_TARGET_KIND_ESP32 = 0,
  HX_TARGET_KIND_ESP32C2,
  HX_TARGET_KIND_ESP32C3,
  HX_TARGET_KIND_ESP32C5,
  HX_TARGET_KIND_ESP32C6,
  HX_TARGET_KIND_ESP32S2,
  HX_TARGET_KIND_ESP32S3,
  HX_TARGET_KIND_ESP32P4,
};

struct HxTargetCapsDef {
  HxTargetKind kind;
  const char* name;
  uint8_t gpio_count;
};

// Helper macro shape:
// X(gpio_number, gpio_flags)

#define HX_TARGET_GPIO_CAPS_ESP32C2(X) \
  X(0,  HX_GPIO_CAP_AIO) \
  X(1,  HX_GPIO_CAP_AIO) \
  X(2,  HX_GPIO_CAP_AIO) \
  X(3,  HX_GPIO_CAP_AIO) \
  X(4,  HX_GPIO_CAP_AIO) \
  X(5,  HX_GPIO_CAP_IO) \
  X(6,  HX_GPIO_CAP_IO) \
  X(7,  HX_GPIO_CAP_IO) \
  X(8,  HX_GPIO_CAP_IO | HX_GPIO_CAP_STRAP) \
  X(9,  HX_GPIO_CAP_IO | HX_GPIO_CAP_STRAP) \
  X(10, HX_GPIO_CAP_IO) \
  X(11, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(12, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(13, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(14, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(15, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(16, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(17, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(18, HX_GPIO_CAP_IO) \
  X(19, HX_GPIO_CAP_IO | HX_GPIO_CAP_DEFAULT_RX0) \
  X(20, HX_GPIO_CAP_IO | HX_GPIO_CAP_DEFAULT_TX0)

#define HX_TARGET_GPIO_CAPS_ESP32C3(X) \
  X(0,  HX_GPIO_CAP_AIO) \
  X(1,  HX_GPIO_CAP_AIO) \
  X(2,  HX_GPIO_CAP_AIO) \
  X(3,  HX_GPIO_CAP_AIO) \
  X(4,  HX_GPIO_CAP_AIO) \
  X(5,  HX_GPIO_CAP_AIO) \
  X(6,  HX_GPIO_CAP_IO) \
  X(7,  HX_GPIO_CAP_IO) \
  X(8,  HX_GPIO_CAP_IO) \
  X(9,  HX_GPIO_CAP_IO) \
  X(10, HX_GPIO_CAP_IO) \
  X(11, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(12, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(13, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(14, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(15, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(16, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(17, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(18, HX_GPIO_CAP_IO | HX_GPIO_CAP_USB) \
  X(19, HX_GPIO_CAP_IO | HX_GPIO_CAP_USB) \
  X(20, HX_GPIO_CAP_IO | HX_GPIO_CAP_DEFAULT_RX0) \
  X(21, HX_GPIO_CAP_IO | HX_GPIO_CAP_DEFAULT_TX0)

#define HX_TARGET_GPIO_CAPS_ESP32C5(X) \
  X(0,  HX_GPIO_CAP_IO) \
  X(1,  HX_GPIO_CAP_AIO) \
  X(2,  HX_GPIO_CAP_AIO) \
  X(3,  HX_GPIO_CAP_AIO) \
  X(4,  HX_GPIO_CAP_AIO) \
  X(5,  HX_GPIO_CAP_AIO) \
  X(6,  HX_GPIO_CAP_AIO) \
  X(7,  HX_GPIO_CAP_AIO) \
  X(8,  HX_GPIO_CAP_IO) \
  X(9,  HX_GPIO_CAP_IO) \
  X(10, HX_GPIO_CAP_IO) \
  X(11, HX_GPIO_CAP_IO) \
  X(12, HX_GPIO_CAP_IO) \
  X(13, HX_GPIO_CAP_IO) \
  X(14, HX_GPIO_CAP_IO) \
  X(15, HX_GPIO_CAP_IO) \
  X(16, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(17, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(18, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(19, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(20, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(21, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(22, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(23, HX_GPIO_CAP_IO) \
  X(24, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(25, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(26, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(27, HX_GPIO_CAP_IO) \
  X(28, HX_GPIO_CAP_IO) \
  X(29, HX_GPIO_CAP_IO)

#define HX_TARGET_GPIO_CAPS_ESP32C6(X) \
  X(0,  HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER) \
  X(1,  HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER) \
  X(2,  HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER) \
  X(3,  HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER) \
  X(4,  HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER | HX_GPIO_CAP_STRAP) \
  X(5,  HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER | HX_GPIO_CAP_STRAP) \
  X(6,  HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER) \
  X(7,  HX_GPIO_CAP_IO  | HX_GPIO_CAP_LOWPOWER) \
  X(8,  HX_GPIO_CAP_IO  | HX_GPIO_CAP_STRAP) \
  X(9,  HX_GPIO_CAP_IO  | HX_GPIO_CAP_STRAP) \
  X(10, HX_GPIO_CAP_IO) \
  X(11, HX_GPIO_CAP_IO) \
  X(12, HX_GPIO_CAP_IO | HX_GPIO_CAP_USB) \
  X(13, HX_GPIO_CAP_IO | HX_GPIO_CAP_USB) \
  X(14, HX_GPIO_CAP_IO) \
  X(15, HX_GPIO_CAP_IO | HX_GPIO_CAP_STRAP) \
  X(16, HX_GPIO_CAP_IO | HX_GPIO_CAP_DEFAULT_TX0) \
  X(17, HX_GPIO_CAP_IO | HX_GPIO_CAP_DEFAULT_RX0) \
  X(18, HX_GPIO_CAP_IO) \
  X(19, HX_GPIO_CAP_IO) \
  X(20, HX_GPIO_CAP_IO) \
  X(21, HX_GPIO_CAP_IO) \
  X(22, HX_GPIO_CAP_IO) \
  X(23, HX_GPIO_CAP_IO) \
  X(24, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH | HX_GPIO_CAP_PSRAM) \
  X(25, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(26, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(27, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(28, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(29, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(30, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH)

#define HX_TARGET_GPIO_CAPS_ESP32S2(X) \
  X(0,  HX_GPIO_CAP_IO  | HX_GPIO_CAP_LOWPOWER | HX_GPIO_CAP_STRAP) \
  X(1,  HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER) \
  X(2,  HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER) \
  X(3,  HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER) \
  X(4,  HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER) \
  X(5,  HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER) \
  X(6,  HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER) \
  X(7,  HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER) \
  X(8,  HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER) \
  X(9,  HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER) \
  X(10, HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER) \
  X(11, HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER) \
  X(12, HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER) \
  X(13, HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER) \
  X(14, HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER) \
  X(15, HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER) \
  X(16, HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER) \
  X(17, HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER) \
  X(18, HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER) \
  X(19, HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER) \
  X(20, HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER) \
  X(21, HX_GPIO_CAP_IO  | HX_GPIO_CAP_LOWPOWER) \
  X(22, 0) \
  X(23, 0) \
  X(24, 0) \
  X(25, 0) \
  X(26, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH | HX_GPIO_CAP_PSRAM) \
  X(27, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(28, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(29, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(30, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(31, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(32, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(33, HX_GPIO_CAP_IO) \
  X(34, HX_GPIO_CAP_IO) \
  X(35, HX_GPIO_CAP_IO) \
  X(36, HX_GPIO_CAP_IO) \
  X(37, HX_GPIO_CAP_IO) \
  X(38, HX_GPIO_CAP_IO) \
  X(39, HX_GPIO_CAP_IO) \
  X(40, HX_GPIO_CAP_IO) \
  X(41, HX_GPIO_CAP_IO) \
  X(42, HX_GPIO_CAP_IO) \
  X(43, HX_GPIO_CAP_IO | HX_GPIO_CAP_DEFAULT_TX0) \
  X(44, HX_GPIO_CAP_IO | HX_GPIO_CAP_DEFAULT_RX0) \
  X(45, HX_GPIO_CAP_IO | HX_GPIO_CAP_STRAP) \
  X(46, HX_GPIO_CAP_IN | HX_GPIO_CAP_INPUT_ONLY | HX_GPIO_CAP_STRAP)

#define HX_TARGET_GPIO_CAPS_ESP32S3(X) \
  X(0,  HX_GPIO_CAP_IO  | HX_GPIO_CAP_LOWPOWER | HX_GPIO_CAP_STRAP) \
  X(1,  HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER | HX_GPIO_CAP_TOUCH) \
  X(2,  HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER | HX_GPIO_CAP_TOUCH) \
  X(3,  HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER | HX_GPIO_CAP_TOUCH | HX_GPIO_CAP_STRAP) \
  X(4,  HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER | HX_GPIO_CAP_TOUCH) \
  X(5,  HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER | HX_GPIO_CAP_TOUCH) \
  X(6,  HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER | HX_GPIO_CAP_TOUCH) \
  X(7,  HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER | HX_GPIO_CAP_TOUCH) \
  X(8,  HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER | HX_GPIO_CAP_TOUCH) \
  X(9,  HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER | HX_GPIO_CAP_TOUCH) \
  X(10, HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER | HX_GPIO_CAP_TOUCH) \
  X(11, HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER | HX_GPIO_CAP_TOUCH) \
  X(12, HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER | HX_GPIO_CAP_TOUCH) \
  X(13, HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER | HX_GPIO_CAP_TOUCH) \
  X(14, HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER | HX_GPIO_CAP_TOUCH) \
  X(15, HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER) \
  X(16, HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER) \
  X(17, HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER) \
  X(18, HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER) \
  X(19, HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER | HX_GPIO_CAP_USB) \
  X(20, HX_GPIO_CAP_AIO | HX_GPIO_CAP_LOWPOWER | HX_GPIO_CAP_USB) \
  X(21, HX_GPIO_CAP_IO  | HX_GPIO_CAP_LOWPOWER) \
  X(22, 0) \
  X(23, 0) \
  X(24, 0) \
  X(25, 0) \
  X(26, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(27, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(28, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(29, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(30, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(31, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(32, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(33, HX_GPIO_CAP_VALID | HX_GPIO_CAP_PSRAM) \
  X(34, HX_GPIO_CAP_VALID | HX_GPIO_CAP_PSRAM) \
  X(35, HX_GPIO_CAP_VALID | HX_GPIO_CAP_PSRAM) \
  X(36, HX_GPIO_CAP_VALID | HX_GPIO_CAP_PSRAM) \
  X(37, HX_GPIO_CAP_VALID | HX_GPIO_CAP_PSRAM) \
  X(38, HX_GPIO_CAP_IO) \
  X(39, HX_GPIO_CAP_IO) \
  X(40, HX_GPIO_CAP_IO) \
  X(41, HX_GPIO_CAP_IO) \
  X(42, HX_GPIO_CAP_IO) \
  X(43, HX_GPIO_CAP_IO | HX_GPIO_CAP_DEFAULT_TX0) \
  X(44, HX_GPIO_CAP_IO | HX_GPIO_CAP_DEFAULT_RX0) \
  X(45, HX_GPIO_CAP_IO | HX_GPIO_CAP_STRAP) \
  X(46, HX_GPIO_CAP_IO | HX_GPIO_CAP_STRAP) \
  X(47, HX_GPIO_CAP_IO) \
  X(48, HX_GPIO_CAP_IO)

#define HX_TARGET_GPIO_CAPS_ESP32P4(X) \
  X(0,  HX_GPIO_CAP_IO  | HX_GPIO_CAP_LOWPOWER) \
  X(1,  HX_GPIO_CAP_IO  | HX_GPIO_CAP_LOWPOWER) \
  X(2,  HX_GPIO_CAP_IO  | HX_GPIO_CAP_LOWPOWER | HX_GPIO_CAP_TOUCH) \
  X(3,  HX_GPIO_CAP_IO  | HX_GPIO_CAP_LOWPOWER | HX_GPIO_CAP_TOUCH) \
  X(4,  HX_GPIO_CAP_IO  | HX_GPIO_CAP_LOWPOWER | HX_GPIO_CAP_TOUCH) \
  X(5,  HX_GPIO_CAP_IO  | HX_GPIO_CAP_LOWPOWER | HX_GPIO_CAP_TOUCH) \
  X(6,  HX_GPIO_CAP_IO  | HX_GPIO_CAP_LOWPOWER | HX_GPIO_CAP_TOUCH) \
  X(7,  HX_GPIO_CAP_IO  | HX_GPIO_CAP_LOWPOWER | HX_GPIO_CAP_TOUCH) \
  X(8,  HX_GPIO_CAP_IO  | HX_GPIO_CAP_LOWPOWER | HX_GPIO_CAP_TOUCH) \
  X(9,  HX_GPIO_CAP_IO  | HX_GPIO_CAP_LOWPOWER | HX_GPIO_CAP_TOUCH) \
  X(10, HX_GPIO_CAP_IO  | HX_GPIO_CAP_LOWPOWER | HX_GPIO_CAP_TOUCH) \
  X(11, HX_GPIO_CAP_IO  | HX_GPIO_CAP_LOWPOWER | HX_GPIO_CAP_TOUCH) \
  X(12, HX_GPIO_CAP_IO  | HX_GPIO_CAP_LOWPOWER | HX_GPIO_CAP_TOUCH) \
  X(13, HX_GPIO_CAP_IO  | HX_GPIO_CAP_LOWPOWER | HX_GPIO_CAP_TOUCH) \
  X(14, HX_GPIO_CAP_IO  | HX_GPIO_CAP_LOWPOWER | HX_GPIO_CAP_TOUCH) \
  X(15, HX_GPIO_CAP_IO  | HX_GPIO_CAP_LOWPOWER | HX_GPIO_CAP_TOUCH) \
  X(16, HX_GPIO_CAP_AIO) \
  X(17, HX_GPIO_CAP_AIO) \
  X(18, HX_GPIO_CAP_AIO) \
  X(19, HX_GPIO_CAP_AIO) \
  X(20, HX_GPIO_CAP_AIO) \
  X(21, HX_GPIO_CAP_AIO) \
  X(22, HX_GPIO_CAP_AIO) \
  X(23, HX_GPIO_CAP_AIO) \
  X(24, HX_GPIO_CAP_IO) \
  X(25, HX_GPIO_CAP_IO) \
  X(26, HX_GPIO_CAP_IO) \
  X(27, HX_GPIO_CAP_IO) \
  X(28, HX_GPIO_CAP_IO) \
  X(29, HX_GPIO_CAP_IO) \
  X(30, HX_GPIO_CAP_IO) \
  X(31, HX_GPIO_CAP_IO) \
  X(32, HX_GPIO_CAP_IO) \
  X(33, HX_GPIO_CAP_IO) \
  X(34, HX_GPIO_CAP_IO | HX_GPIO_CAP_STRAP) \
  X(35, HX_GPIO_CAP_IO | HX_GPIO_CAP_STRAP) \
  X(36, HX_GPIO_CAP_IO | HX_GPIO_CAP_STRAP) \
  X(37, HX_GPIO_CAP_IO | HX_GPIO_CAP_STRAP | HX_GPIO_CAP_DEFAULT_TX0) \
  X(38, HX_GPIO_CAP_IO | HX_GPIO_CAP_STRAP | HX_GPIO_CAP_DEFAULT_RX0) \
  X(39, HX_GPIO_CAP_IO) \
  X(40, HX_GPIO_CAP_IO) \
  X(41, HX_GPIO_CAP_IO) \
  X(42, HX_GPIO_CAP_IO) \
  X(43, HX_GPIO_CAP_IO) \
  X(44, HX_GPIO_CAP_IO) \
  X(45, HX_GPIO_CAP_IO) \
  X(46, HX_GPIO_CAP_IO) \
  X(47, HX_GPIO_CAP_IO) \
  X(48, HX_GPIO_CAP_IO) \
  X(49, HX_GPIO_CAP_AIO) \
  X(50, HX_GPIO_CAP_AIO) \
  X(51, HX_GPIO_CAP_AIO) \
  X(52, HX_GPIO_CAP_AIO) \
  X(53, HX_GPIO_CAP_AIO) \
  X(54, HX_GPIO_CAP_AIO)

#define HX_TARGET_GPIO_CAPS_ESP32(X) \
  X(0,  HX_GPIO_CAP_IO  | HX_GPIO_CAP_TOUCH) \
  X(1,  HX_GPIO_CAP_IO  | HX_GPIO_CAP_DEFAULT_TX0) \
  X(2,  HX_GPIO_CAP_IO  | HX_GPIO_CAP_TOUCH) \
  X(3,  HX_GPIO_CAP_IO  | HX_GPIO_CAP_DEFAULT_RX0) \
  X(4,  HX_GPIO_CAP_IO  | HX_GPIO_CAP_TOUCH) \
  X(5,  HX_GPIO_CAP_IO) \
  X(6,  HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(7,  HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(8,  HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(9,  HX_GPIO_CAP_IO) \
  X(10, HX_GPIO_CAP_IO) \
  X(11, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(12, HX_GPIO_CAP_AIO | HX_GPIO_CAP_TOUCH | HX_GPIO_CAP_STRAP) \
  X(13, HX_GPIO_CAP_AIO | HX_GPIO_CAP_TOUCH) \
  X(14, HX_GPIO_CAP_AIO | HX_GPIO_CAP_TOUCH) \
  X(15, HX_GPIO_CAP_AIO | HX_GPIO_CAP_TOUCH | HX_GPIO_CAP_STRAP) \
  X(16, HX_GPIO_CAP_IO) \
  X(17, HX_GPIO_CAP_IO) \
  X(18, HX_GPIO_CAP_IO) \
  X(19, HX_GPIO_CAP_IO) \
  X(20, 0) \
  X(21, HX_GPIO_CAP_IO) \
  X(22, HX_GPIO_CAP_IO) \
  X(23, HX_GPIO_CAP_IO) \
  X(24, 0) \
  X(25, HX_GPIO_CAP_AIO) \
  X(26, HX_GPIO_CAP_AIO) \
  X(27, HX_GPIO_CAP_AIO | HX_GPIO_CAP_TOUCH) \
  X(28, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(29, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(30, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(31, HX_GPIO_CAP_VALID | HX_GPIO_CAP_FLASH) \
  X(32, HX_GPIO_CAP_AIO | HX_GPIO_CAP_TOUCH) \
  X(33, HX_GPIO_CAP_AIO | HX_GPIO_CAP_TOUCH) \
  X(34, HX_GPIO_CAP_IN  | HX_GPIO_CAP_INPUT_ONLY) \
  X(35, HX_GPIO_CAP_IN  | HX_GPIO_CAP_INPUT_ONLY) \
  X(36, HX_GPIO_CAP_IN  | HX_GPIO_CAP_INPUT_ONLY | HX_GPIO_CAP_ANALOG) \
  X(37, 0) \
  X(38, 0) \
  X(39, HX_GPIO_CAP_IN  | HX_GPIO_CAP_INPUT_ONLY | HX_GPIO_CAP_ANALOG)

// Target descriptors.
static constexpr HxTargetCapsDef HX_TARGET_CAPS_ESP32_DEF    = { HX_TARGET_KIND_ESP32,    "esp32",    40 };
static constexpr HxTargetCapsDef HX_TARGET_CAPS_ESP32C2_DEF  = { HX_TARGET_KIND_ESP32C2,  "esp32c2",  21 };
static constexpr HxTargetCapsDef HX_TARGET_CAPS_ESP32C3_DEF  = { HX_TARGET_KIND_ESP32C3,  "esp32c3",  22 };
static constexpr HxTargetCapsDef HX_TARGET_CAPS_ESP32C5_DEF  = { HX_TARGET_KIND_ESP32C5,  "esp32c5",  30 };
static constexpr HxTargetCapsDef HX_TARGET_CAPS_ESP32C6_DEF  = { HX_TARGET_KIND_ESP32C6,  "esp32c6",  31 };
static constexpr HxTargetCapsDef HX_TARGET_CAPS_ESP32S2_DEF  = { HX_TARGET_KIND_ESP32S2,  "esp32s2",  47 };
static constexpr HxTargetCapsDef HX_TARGET_CAPS_ESP32S3_DEF  = { HX_TARGET_KIND_ESP32S3,  "esp32s3",  49 };
static constexpr HxTargetCapsDef HX_TARGET_CAPS_ESP32P4_DEF  = { HX_TARGET_KIND_ESP32P4,  "esp32p4",  55 };

#if defined(CONFIG_IDF_TARGET_ESP32C2)
  #define HX_TARGET_CAPS_CURRENT_DEF HX_TARGET_CAPS_ESP32C2_DEF
  #define HX_TARGET_GPIO_CAPS_CURRENT(X) HX_TARGET_GPIO_CAPS_ESP32C2(X)
#elif defined(CONFIG_IDF_TARGET_ESP32C3)
  #define HX_TARGET_CAPS_CURRENT_DEF HX_TARGET_CAPS_ESP32C3_DEF
  #define HX_TARGET_GPIO_CAPS_CURRENT(X) HX_TARGET_GPIO_CAPS_ESP32C3(X)
#elif defined(CONFIG_IDF_TARGET_ESP32C5)
  #define HX_TARGET_CAPS_CURRENT_DEF HX_TARGET_CAPS_ESP32C5_DEF
  #define HX_TARGET_GPIO_CAPS_CURRENT(X) HX_TARGET_GPIO_CAPS_ESP32C5(X)
#elif defined(CONFIG_IDF_TARGET_ESP32C6)
  #define HX_TARGET_CAPS_CURRENT_DEF HX_TARGET_CAPS_ESP32C6_DEF
  #define HX_TARGET_GPIO_CAPS_CURRENT(X) HX_TARGET_GPIO_CAPS_ESP32C6(X)
#elif defined(CONFIG_IDF_TARGET_ESP32S2)
  #define HX_TARGET_CAPS_CURRENT_DEF HX_TARGET_CAPS_ESP32S2_DEF
  #define HX_TARGET_GPIO_CAPS_CURRENT(X) HX_TARGET_GPIO_CAPS_ESP32S2(X)
#elif defined(CONFIG_IDF_TARGET_ESP32S3)
  #define HX_TARGET_CAPS_CURRENT_DEF HX_TARGET_CAPS_ESP32S3_DEF
  #define HX_TARGET_GPIO_CAPS_CURRENT(X) HX_TARGET_GPIO_CAPS_ESP32S3(X)
#elif defined(CONFIG_IDF_TARGET_ESP32P4)
  #define HX_TARGET_CAPS_CURRENT_DEF HX_TARGET_CAPS_ESP32P4_DEF
  #define HX_TARGET_GPIO_CAPS_CURRENT(X) HX_TARGET_GPIO_CAPS_ESP32P4(X)
#else
  #define HX_TARGET_CAPS_CURRENT_DEF HX_TARGET_CAPS_ESP32_DEF
  #define HX_TARGET_GPIO_CAPS_CURRENT(X) HX_TARGET_GPIO_CAPS_ESP32(X)
#endif
